plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md

#remote_theme: BGameiro76/jekyll-theme-prologue
theme: jekyll-theme-cayman
